### ISSUE TITLE
中文的支持

### ISSUE THREAD

**Issue by wanghao-007** [BrasD99/HeyGenClone#1]
你好，达瓦里希。对于中文的翻译，目前有没有相关的解决方案，方便的话你可以透露一下，我想实现一下啊。谢谢

**Comment by BrasD99** [comment]
Hello @wanghao-007! Glad to see your interest in my solution.

I think it's possible to try Chinese translation right now. The main point to consider: transcription of audio from the input video is obtained through Whisper, so far there is only support for English. Then HeyGenClone translates the transcription into the required language using googletrans. Voice cloning is performed using the Coqui solution, where Chinese language support is declared. From the point of view of lip sync, I don't see any problems.

But I want to note that my solution is still at the stage of active development. There are still a lot of things I want to fix and improve. I have not tested the Chinese translation yet, but I will be glad to receive feedback on this.

And, of course, I will be especially glad to see suggestions for improvement. I need contributors with new ideas.

**Comment by wanghao-007** [comment]
> 你好@wanghao-007！很高兴看到您对我的解决方案感兴趣。
> 
> 我认为现在可以尝试中文翻译。需要考虑的要点：输入视频的音频转录是通过 Whisper 获得的，目前仅支持英语。然后 HeyGenClone 使用 googletrans 将转录翻译成所需的语言。语音克隆是使用 Coqui 解决方案执行的，其中声明支持中文。从口型同步的角度来看，我没有看到任何问题。
> 
> 但我想指出的是，我的解决方案仍处于积极开发阶段。还有很多东西我想要修复和改进。我还没有测试中文翻译，但我很高兴收到对此的反馈。
> 
> 当然，我会特别高兴看到改进的建议。我需要有新想法的贡献者。

感谢你的回复。你的这个项目很复杂，牵涉到的深度学习方向很多。我复现了这个项目后跑了几个视频，我发现一个小问题，对speaker的面部检测后昨晚嘴形变化后再粘回去会出现一些错位和叠加现象，显得不是很自然。另外如果使用在线翻译的话，可以使用openai的api接口，会不会更快一些？中文的话，我还没有的思路，主要在中文嘴形怎么匹配我还比较陌生，我需要再看看你的项目细节。

**Comment by wanghao-007** [comment]
> 你好@wanghao-007！很高兴看到您对我的解决方案感兴趣。
> 
> 我认为现在可以尝试中文翻译。需要考虑的要点：输入视频的音频回放是通过 Whisper 获得的，目前仅支持英语。然后 HeyGenClone 使用 googletrans 将调整翻译成所需的语言。语音克隆是使用 Coqui 解决方案执行的，其中声明支持中文。从口型同步的角度来看，我没有看到任何问题。
> 
> 但我想指出的是，我的解决方案仍处于积极开发阶段。还有很多东西我想要修复和改进。我还没有测试中文翻译，但我很高兴收到这个反馈。
> 
> 当然，我会特别高兴看到改进的建议。我需要有新想法的贡献者。

谢谢你的回复。你的这个项目很复杂，涉及到很多深度学习方向。我复现了这个项目后跑了几个视频，我发现一个小问题，对说话者的面部检测后做完嘴形变化再粘回去会出现一些视觉错位和贴图的叠加现象，不是很自然。另外如果使用在线翻译的话，可以使用openai的一些api接口，会不会更快一些？中文的话，我还没有办法，主要在中文嘴形怎么匹配我还比较陌生，我需要再看看你的项目细节。

**Comment by wanghao-007** [comment]
> Hello @wanghao-007! Glad to see your interest in my solution.
> 
> I think it's possible to try Chinese translation right now. The main point to consider: transcription of audio from the input video is obtained through Whisper, so far there is only support for English. Then HeyGenClone translates the transcription into the required language using googletrans. Voice cloning is performed using the Coqui solution, where Chinese language support is declared. From the point of view of lip sync, I don't see any problems.
> 
> But I want to note that my solution is still at the stage of active development. There are still a lot of things I want to fix and improve. I have not tested the Chinese translation yet, but I will be glad to receive feedback on this.
> 
> And, of course, I will be especially glad to see suggestions for improvement. I need contributors with new ideas.

谢谢你的回复。你的这个项目很复杂，涉及到很多深度学习方向。我复现了这个项目后跑了几个视频，我发现一个小问题，对说话者的面部检测后做完嘴形变化再粘回去会出现一些视觉错位和贴图的叠加现象，不是很自然。另外如果使用在线翻译的话，可以使用openai的一些api接口，会不会更快一些？中文的话，我还没有办法，主要在中文嘴形怎么匹配我还比较陌生，我需要再看看你的项目细节。

**Comment by BrasD99** [comment]
@wanghao-007 Of course, I can use OpenAI, but you need to understand that it is not available in Russia. I don't see the point of using a VPN, it slows down development. At the moment, I will not touch the translation functionality.

As for lip sync: I have already encountered this problem and am thinking about solving it. Accuracy is lame - this is a fact.
