### ISSUE TITLE
i need help with hf_token

### ISSUE THREAD

**Issue by qq357075581** [BrasD99/HeyGenClone#14]
I've already set up my hf_token,but there is the following error.
![error](https://github.com/BrasD99/HeyGenClone/assets/26922978/d1e9fb7f-07ca-4f43-b36e-6597e926eeb3)
I set two points
![pos1](https://github.com/BrasD99/HeyGenClone/assets/26922978/b1c2bc8b-5433-4332-a4c2-61f64391132e)
![pos2](https://github.com/BrasD99/HeyGenClone/assets/26922978/633928fc-2c6c-4365-89d0-dc356c9e8818)

**Comment by BrasD99** [comment]
From Readme: In config.json file change HF_TOKEN argument. It is your HuggingFace token. **Visit [speaker-diarization](https://hf.co/pyannote/speaker-diarization), [segmentation](https://hf.co/pyannote/segmentation) and accept user conditions**
